services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${WEB_PORT}:80"
    volumes:
      - ../composer.json:/module/composer.json:ro
      - ../src:/module/src
      - ../tests:/module/tests:ro
      - ../_config:/module/_config:ro
      - vendor:/app/vendor
    depends_on:
      db:
        condition: service_healthy
    environment:
      SS_DATABASE_SERVER: db
      SS_DATABASE_NAME: silverstripe
      SS_DATABASE_USERNAME: silverstripe
      SS_DATABASE_PASSWORD: silverstripe
      SS_DEFAULT_ADMIN_USERNAME: admin
      SS_DEFAULT_ADMIN_PASSWORD: admin
      SS_ENVIRONMENT_TYPE: dev
      SS_PHPUNIT_FLUSH: 1

  db:
    image: mysql:8
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - db-data:/var/lib/mysql
      - ./db-init:/docker-entrypoint-initdb.d:ro
    environment:
      MYSQL_DATABASE: silverstripe
      MYSQL_USER: silverstripe
      MYSQL_PASSWORD: silverstripe
      MYSQL_ROOT_PASSWORD: root
    healthcheck:
      test: mysqladmin ping -h localhost
      interval: 5s
      retries: 10

volumes:
  vendor:
  db-data:
